### PUT - Atualizar dados de um usuário
PUT http://localhost:5050/api/v1/users/id
Content-Type: application/json
Authorization: Bearer <SEU_TOKEN_AQUI>

{
  "userName": "gustavo_dev_update",
  "email": "gustavo.dev.update@example.com",
  "password": "senhaForte123"
}
