server:
  port: 5050

spring:
  application:
    name: project-task-app

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

  springdoc:
    swagger-ui:
      path: /swagger-ui.html # http://localhost:5055/swagger-ui.html