server:
  port: 5050

spring:
  application:
    name: project-task-app

  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

  jwt:
    secret: ${JWT_SECRET}

  flyway:
    enabled: true
    locations: classpath:db/migration

  springdoc:
    swagger-ui:
      path: /swagger-ui.html # http://localhost:5050/swagger-ui.html

  jackson:
    time-zone: America/Sao_Paulo

management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      access: unrestricted
    prometheus:
      access: unrestricted