server:
  port: 5050

spring:
  application:
    name: project-task-app-local

  datasource:
    url: jdbc:postgresql://localhost:5051/db-project-task
    username: user_gustavo
    password: senha_gustavo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}

  flyway:
    enabled: true
    locations: classpath:db/migration

  springdoc:
    swagger-ui:
      path: /swagger-ui.html # http://localhost:5050/swagger-ui.html

  jackson:
    time-zone: America/Sao_Paulo

management:
  endpoints:
    web:
      exposure:
        include: 'health,prometheus'
  endpoint:
    health:
      access: unrestricted
    prometheus:
      access: unrestricted







